"""SQLAlchemy-free, cloud-SDK-free mailbox credential secret-store contract.

ConnectorAccount stores only an opaque credential_ref. Secret material lives
behind this port, never in relational entities. Version is opaque.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class NewCommunicationCredential:
    """Persistence-neutral input for storing opaque mailbox credential material."""

    credential_ref: str
    provider: str
    secret_material: bytes = field(repr=False)

    def __repr__(self) -> str:
        return f"NewCommunicationCredential(provider={self.provider!r})"


@dataclass(frozen=True, slots=True)
class CommunicationCredentialRecord:
    """Opaque stored mailbox credential. Secret material is omitted from repr."""

    credential_ref: str
    provider: str
    version: str
    secret_material: bytes = field(repr=False)

    def __repr__(self) -> str:
        return (
            "CommunicationCredentialRecord("
            f"provider={self.provider!r}, version=...)"
        )


class CommunicationCredentialStore(ABC):
    """Store opaque mailbox credential material outside relational persistence.

    Locators are server-generated by callers. This port does not mint
    credential_ref values. Compare-and-set replacement is the multi-instance
    safety mechanism; implementations must not blindly overwrite.
    """

    @abstractmethod
    def create(
        self,
        credential: NewCommunicationCredential,
    ) -> CommunicationCredentialRecord:
        """Insert credential material for a new locator.

        Fail if the locator already exists. Do not overwrite.
        """

    @abstractmethod
    def get(self, credential_ref: str) -> CommunicationCredentialRecord | None:
        """Return stored material, or None when the locator is unknown."""

    @abstractmethod
    def replace_if_version(
        self,
        credential_ref: str,
        expected_version: str,
        secret_material: bytes,
    ) -> CommunicationCredentialRecord | None:
        """Replace material only when the stored version matches ``expected_version``.

        Success returns the new record with a new opaque version. A version
        mismatch or unknown locator returns None and must not overwrite the
        winner.
        """

    @abstractmethod
    def delete(self, credential_ref: str) -> None:
        """Remove stored material. Unknown locators are a no-op."""
