"""Provider-independent communication domain for ECI Platform."""

from app.domain.enums import (
    ApplicationRole,
    AttachmentDisposition,
    AttachmentExtractedContentStatus,
    AttachmentKind,
    AttachmentScanVerdict,
    CommunicationCapability,
    ConnectorAccountStatus,
    MailboxAuthorizationProvider,
    MailboxAuthorizationPurpose,
    MessageCategory,
    PriorityLevel,
    SourceType,
    WorkflowActionStatus,
    WorkflowActionType,
)
from app.domain.exceptions import InvalidWorkflowTransitionError
from app.domain.interfaces import (
    AIProvider,
    AttachmentParser,
    AttachmentScanner,
    CommunicationConnector,
)
from app.domain.models import (
    ActionItem,
    AIImageInput,
    AttachmentAnalysis,
    AttachmentContent,
    AttachmentMetadata,
    AttachmentTextSection,
    CommunicationAnalysis,
    CommunicationMessage,
    DraftReply,
    MessageMetadata,
    ParsedAttachment,
    Priority,
    Summary,
    WorkflowAction,
)
from app.domain.schemas import CommunicationAnalysisResult, CommunicationRequest

__all__ = [
    "AIImageInput",
    "AIProvider",
    "ActionItem",
    "ApplicationRole",
    "AttachmentAnalysis",
    "AttachmentContent",
    "AttachmentDisposition",
    "AttachmentExtractedContentStatus",
    "AttachmentKind",
    "AttachmentMetadata",
    "AttachmentParser",
    "AttachmentScanVerdict",
    "AttachmentScanner",
    "AttachmentTextSection",
    "CommunicationAnalysis",
    "CommunicationAnalysisResult",
    "CommunicationCapability",
    "CommunicationConnector",
    "CommunicationMessage",
    "CommunicationRequest",
    "ConnectorAccountStatus",
    "DraftReply",
    "InvalidWorkflowTransitionError",
    "MailboxAuthorizationProvider",
    "MailboxAuthorizationPurpose",
    "MessageCategory",
    "MessageMetadata",
    "ParsedAttachment",
    "Priority",
    "PriorityLevel",
    "SourceType",
    "Summary",
    "WorkflowAction",
    "WorkflowActionStatus",
    "WorkflowActionType",
]
